@api =  http://localhost:3001


GET {{api}}/pokemons

###

GET {{api}}/pokemons/bbb3b982-5f38-4d6e-8cd2-620aabf68c4f

###

GET {{api}}/types


###
POST {{api}}/pokemons
Content-Type: application/json

{
    "name": "pepino",
    "life": 50,
    "attack": 90,
    "defense": 60,
    "speed": 100,
    "height": 6,
    "weight": 70,
    "types": ["fire", "normal"]
}